### ISSUE TITLE
REGISTRATION

### ISSUE THREAD

**Issue by mmayorivera** [mohitmshah09/best-you#1]
when receiving the code confirmation use a mask instead of an input per digit. Using that I can still type more than one digit per input

**Comment by mmayorivera** [comment]
Also when I am in the last step where I asked to upload an image for avatar show a default avatar, and when Is ready to sign up, when click redirect to the home page, do not forget to validate passwords

**Comment by mohitmshah09** [comment]
> when receiving the code confirmation use a mask instead of an input per digit. Using that I can still type more than one digit per input

ok, we will be using ng-otp-input npm.

**Comment by mohitmshah09** [comment]
> Also when I am in the last step where I asked to upload an image for avatar show a default avatar, and when Is ready to sign up, when click redirect to the home page, do not forget to validate passwords
